### ISSUE TITLE
publish fork to npm

### ISSUE THREAD

**Issue by gitbreaker222** [gitbreaker222/svelte-virtual-list#1]
PR to fix scroll position issues has been open for about half a year unnoticed.

https://github.com/sveltejs/svelte-virtual-list/pull/52#issuecomment-873869582

Following @stalkerg 's advice, this fork should become an npm package itself. In Preparation for identity, several infos need to be created:

- name: `svelte-virtual-list-ce` (ce short for "community edition")
  - it is still a fork of `svelte-virtual-list` so the name should stay as close as the code to the original
- logo: ![svelte-virtual-list-ce](https://user-images.githubusercontent.com/4787651/124776545-d25a5080-df3f-11eb-824a-6e63fb8b9d43.jpg)
  - I think it deserves an iconic visual representation. This is just a conceptual sketch though. It should have Sveltes color-scheme and tell about the visual part of a list beeing "full" there and the parts outside beeing just a light-weight outline

**Comment by mellson** [comment]
@gitbreaker222 did you publish this fork? I tried searching for `svelte-virtual-list-ce` on npm but can't seem to find it 🤔

**Comment by gitbreaker222** [comment]
well no I did not complete it as I lack of motivation doing programming things alone in my free time. Also I've never published anything on npm - I think my last state was reading the docs and stopping at the point, where I have to create an account there :see_no_evil: 

I could offer pair programming via discord/matrix/jitsi and expect the thing to be done in about 1 hour ^^ I think we are in the same time zone and tomorrow - sunday between 13:00 - 18:00 I am free

**Comment by mellson** [comment]
@gitbreaker222 that sounds like a great idea! Let's hook up online tomorrow at 13:00 and try to ship this to npm. I'm mellson#5819 on discord. If you add me we can start there.

**Comment by gitbreaker222** [comment]
:information_source: created clean version for logo on feature branch
![logo.png](https://github.com/gitbreaker222/svelte-virtual-list/blob/%2343_scroll-position/logo_svelte-virtual-list-ce.png)

**Comment by mellson** [comment]
Looks great 👍🏻 I just tried to publish a test package to npm - so think we're good to go tomorrow!

**Comment by gitbreaker222** [comment]
https://www.npmjs.com/package/svelte-virtual-list-ce :raised_hands: :tada: 
thx @mellson
